services:
  go:
    entrypoint: go
    environment:
      HOME: /app
    image: golang:1.13
    user: ${UID}:${GID}
    volumes:
      - ".:/app"
    working_dir: /app
  golangci-lint:
    command: golangci-lint run
    environment:
      HOME: /app
    image: golangci/golangci-lint:v1.20.1
    user: ${UID}:${GID}
    volumes:
      - ".:/app"
    working_dir: /app
  influxdb:
    environment:
      INFLUXDB_DB: dev
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: dev
      INFLUXDB_USER_PASSWORD: dev
    image: influxdb:1.7
    ports:
      - "8086:8086"
    restart: "always"
    volumes:
      - "influxdb:/var/lib/influxdb"
version: "3"
volumes:
  influxdb: {}
