name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bin Cache
        uses: actions/cache@v1
        with:
          path: .bin
          key: bin-${{ hashFiles('bin.mk') }}
      - name: Build
        run: make build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./weatherproxy_linux.tar.gz
          asset_name: weatherproxy_linux.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Hash
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./weatherproxy_linux.tar.gz.sha256
          asset_name: weatherproxy_linux.tar.gz.sha256
          asset_content_type: text/plain
