name: workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    if: github.event_name != 'release'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: make lint
  test:
    if: github.event_name != 'release'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: make test
