name: workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    if: github.event_name != 'release'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bin Cache
        uses: actions/cache@v1
        with:
          path: .bin
          key: bin-${{ hashFiles('bin.mk') }}
      - name: Lint
        run: make lint
  test:
    if: github.event_name != 'release'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bin Cache
        uses: actions/cache@v1
        with:
          path: .bin
          key: bin-${{ hashFiles('bin.mk') }}
      - name: Test
        run: |
          make postgresql
          make test
